Code
Pull requests 1
Projects 0
Insights
CS499_MachineLearning_TeamProject/nearestNeaighbor.Rmd
4e4faf8 on Feb 15, 2019
---
output: pdf_document
---

<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{An Introduction to Glmnet}
-->

<a id="top"></a>

# Nearest Neighbor

#### NAU Febuary 15, 2019

> [Introduction](#intro)
> We were tasked with attempting to code a nearest neaighbor algorithm in C++ and R and the task was very challenging. The Enviornment was new for 75% of our group and the project suffered because of it. That being said we did accomplish 3 of the 4 required parts. We ran out of time.
<a id="intro"></a>

## Data set 1: spam

### Matrix of loss values

print out and/or plot the matrix.

comment on difference between NN and baseline.

### Train/validation loss plot

plot the two loss functions.

What is the optimal number of neighbors?

## Data set 2: SAheart

### Matrix of loss values

print out and/or plot the matrix.

comment on difference between NN and baseline.

### Train/validation loss plot

plot the two loss functions.

What is the optimal number of neighbors?

## Data set 3: ...

[Back to Top](#top)




